# Generated by Django 2.1.4 on 2023-03-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='created',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='modified',
        ),
    ]
