# Generated by Django 2.1.4 on 2023-03-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20230327_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.TextField(default='nan', verbose_name='Предмет'),
            preserve_default=False,
        ),
    ]
