# Generated by Django 2.1.4 on 2023-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_subjects_questions_tour3'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='grade',
            field=models.IntegerField(default=5, verbose_name='Класс'),
        ),
    ]
