# Generated by Django 2.1.4 on 2023-05-02 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizprofile_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('time', models.IntegerField(default=5, verbose_name='Время прохождения')),
                ('quiz_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='quiz.QuizProfile')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Subjects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
