# Generated by Django 2.1.4 on 2023-03-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20230327_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AddField(
            model_name='subjects',
            name='num',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Номер класса'),
        ),
    ]
