# Generated by Django 2.1.4 on 2023-03-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20230318_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ManyToManyField(related_name='grades', to='quiz.Subjects'),
        ),
    ]
