# Generated by Django 2.1.4 on 2023-03-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20230327_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='num',
            new_name='grade',
        ),
    ]
