# Generated by Django 2.1.4 on 2023-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20230404_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default=None, upload_to='questions/', verbose_name='Image'),
        ),
    ]
